_target_: src.models.msres_module.MsResLitModule

loss: ${loss}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3

scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [20, 25]
  gamma: 0.5

net:
  _target_: src.models.components.msres.MSResNet
