# @package _global_

defaults:
  - _self_
  - model: realesrgan.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - representation: pu.yaml
  - loss: l1.yaml
  - hydra: default.yaml


data:
  hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_aug
  lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_aug
  batch_size: 1

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
# ckpt_path: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train/runs/2023-03-28_17-55-09/checkpoints/last.ckpt"

log_path:

  linear_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/real_linear_epoch=1130-step=196793.ckpt"

  pu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/real_pu_l1_epoch=2294-step=399329.ckpt"

  pu21_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/real_pu_l1_epoch=2294-step=399329.ckpt"

  mu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/real_pu_l1_epoch=2294-step=399329.ckpt"

  pq_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/real_pq_l1_epoch=2900-step=504773.ckpt"

  linear_pu: "/home/luoleyouluole/Image-Restoration-Experiments/logs/real_linear_pu_epoch=939-step=163559.ckpt"

  linear_pq: "/home/luoleyouluole/Image-Restoration-Experiments/logs/real_linear_pq_epoch=926-step=161297.ckpt"

  linear_smape: "/home/luoleyouluole/Image-Restoration-Experiments/logs/real_linear_smape_epoch=816-step=142157.ckpt"

  linear_mu: "/home/luoleyouluole/Image-Restoration-Experiments/logs/real_linear_mu_epoch=883-step=153815.ckpt"



results_save_path: "/home/luoleyouluole/Image-Restoration-Experiments/data/res_real/"
