# @package _global_

defaults:
  - _self_
  - model: sadnet.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - representation: pu.yaml
  - loss: l1.yaml
  - hydra: default.yaml


data:
  hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_hdr_patchify
  lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_noise_hdr_patchify
  batch_size: 1

task_name: "eval"

log_path:
  linear_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/sadnet_linear_epoch=975-step=68319.ckpt"

  pq_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/sadnet_pq_epoch=1126-step=98048.ckpt"

  pu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/sadnet_pu_epoch=971-step=68039.ckpt"

  linear_smape: "/home/luoleyouluole/Image-Restoration-Experiments/logs/sad_linear_smape_epoch=795-step=55719.ckpt"

  linear_pu: "/home/luoleyouluole/Image-Restoration-Experiments/logs/sad_linear_pu_epoch=851-step=59639.ckpt"

  linear_pq: "/home/luoleyouluole/Image-Restoration-Experiments/logs/sad_linear_pq_epoch=954-step=66849.ckpt"

  linear_mu: "/home/luoleyouluole/Image-Restoration-Experiments/logs/sad_linear_mu_epoch=968-step=67829.ckpt"



results_save_path: "/home/luoleyouluole/Image-Restoration-Experiments/data/res_sad/"
