# @package _global_

defaults:
  - _self_
  - model: edsr.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - representation: pu.yaml
  - loss: pu.yaml
  - hydra: default.yaml


data:
  hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test2/hq
  lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test2/lq
  batch_size: 1

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
# ckpt_path: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train/runs/2023-03-28_17-55-09/checkpoints/last.ckpt"

ckpt_path: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train/runs/2023-04-10_10-04-29/checkpoints/last.ckpt"
