# @package _global_

defaults:
  - _self_
  - model: wdsr.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - representation: pu.yaml
  - loss: l1.yaml
  - hydra: default.yaml


data:
  hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_aug
  lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_aug
  batch_size: 1

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
# ckpt_path: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train/runs/2023-03-28_17-55-09/checkpoints/last.ckpt"

log_path:

  linear_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/wdsr_linear_epoch=1929-step=17999.ckpt"

  pu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/wdsr_pu_epoch=2544-step=23561.ckpt"

  pq_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/wdsr_pq_epoch=2989-step=27449.ckpt"


results_save_path: "/home/luoleyouluole/Image-Restoration-Experiments/data/res_wdsr/"
