# @package _global_

defaults:
  - _self_
  - model: dncnn.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - representation: pu.yaml
  - loss: l1.yaml
  - hydra: default.yaml


# data:
#   hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test
#   lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test
#   batch_size: 1

data:
  hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_hdr
  lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_noise_hdr
  batch_size: 1

task_name: "eval"

tags: ["dev"]


log_path:

  linear_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/dncnn_linear_epoch=409-step=35669.ckpt"

  pq_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/dncnn_pq_epoch=526-step=45848.ckpt"

  pu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/dncnn_pu_epoch=235-step=20531.ckpt"


results_save_path: "/home/luoleyouluole/Image-Restoration-Experiments/data/res_dn/"
