# @package _global_

defaults:
  - _self_
  - model: gfn.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - representation: pu.yaml
  - loss: l1.yaml
  - hydra: default.yaml


data:
  hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_aug
  lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_aug
  batch_size: 1

task_name: "eval"

log_path:
  linear_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/gfn_linear_epoch=959-step=83519.ckpt"

  pq_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/gfn_pq_epoch=981-step=85433.ckpt"

  pu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/gfn_pu_epoch=994-step=86564.ckpt"


results_save_path: "/home/luoleyouluole/Image-Restoration-Experiments/data/res_gfn/"
