# @package _global_

defaults:
  - _self_
  - model: dncnn.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - representation: pu.yaml
  - loss: l1.yaml
  - hydra: default.yaml


# data:
#   hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test
#   lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test
#   batch_size: 1

# data:
#   hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_hdr_aug_patchify
#   lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_noise_hdr_aug_patchify
#   batch_size: 1

data:
  hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_hdr_patchify
  lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_noise_hdr_patchify
  batch_size: 1

task_name: "eval"

tags: ["dev"]


log_path:

  # linear_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/dncnn_linear_epoch=374-step=32624.ckpt"

  # pq_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/dncnn_pq_epoch=943-step=82127.ckpt"

  mu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/dncnn_mu_epoch=1901-step=165473.ckpt"

  # pu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/gfn_pu_epoch=994-step=86564.ckpt"

  # pu21_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/dncnn_pu_epoch=873-step=76037.ckpt"

  # linear_smape: "/home/luoleyouluole/Image-Restoration-Experiments/logs/dncnn_linear_smapeepoch=235-step=20531.ckpt"

  # linear_mu: "/home/luoleyouluole/Image-Restoration-Experiments/logs/dncnn_linear_mu_epoch=916-step=79778.ckpt"

  # linear_pu: "/home/luoleyouluole/Image-Restoration-Experiments/logs/dncnn_linear_pu_epoch=677-step=58985.ckpt"

  # linear_pq: "/home/luoleyouluole/Image-Restoration-Experiments/logs/dncnn_linear_pq_epoch=462-step=40280.ckpt"



results_save_path: "/home/luoleyouluole/Image-Restoration-Experiments/data/res_dn_mu/"
