# @package _global_

defaults:
  - _self_
  - model: mirnetv2.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - representation: pu.yaml
  - loss: l1.yaml
  - hydra: default.yaml


data:
  hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_aug
  lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_aug
  batch_size: 1

task_name: "eval"

log_path:
  linear_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/mirnet_linear_epoch=10-step=12715.ckpt"

  pq_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/mirnetv2_pq_epoch=384-step=445059.ckpt"

  pu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/mirnetv2_pu_epoch=165-step=191895.ckpt"


results_save_path: "/home/luoleyouluole/Image-Restoration-Experiments/data/res_mir/"
