# @package _global_

defaults:
  - _self_
  - model: mirnetv2.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - representation: pu.yaml
  - loss: l1.yaml
  - hydra: default.yaml


data:
  hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_aug_patchify
  lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_aug_patchify
  # hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test
  # lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test
  batch_size: 1

task_name: "eval"

log_path:
  # linear_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/mirnet_linear_epoch=10-step=12715.ckpt"

  # pq_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/mirnetv2_pq_epoch=384-step=445059.ckpt"

  # pu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/mirnetv2_pu_epoch=165-step=191895.ckpt"

  mu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/mirnetv2_mu_epoch=392-step=454307.ckpt"

  pu21_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/mirnetv2_pu21_epoch=18-step=21963.ckpt"

  linear_pu: "/home/luoleyouluole/Image-Restoration-Experiments/logs/mirnetv2_linear_pu_epoch=11-step=13871.ckpt"

  # linear_pq: "/home/luoleyouluole/Image-Restoration-Experiments/logs/mirnetv2_linear_pq_epoch=59-step=69359.ckpt"

  # linear_smape: "/home/luoleyouluole/Image-Restoration-Experiments/logs/mirnetv2_linear_smape_epoch=49-step=57799.ckpt"



results_save_path: "/home/luoleyouluole/Image-Restoration-Experiments/data/res_mir_extra/"
