# @package _global_

defaults:
  - _self_
  - model: edsr.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - representation: pu.yaml
  - loss: l1.yaml
  - hydra: default.yaml


data:
  hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test3/hq
  lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test3/lq
  batch_size: 1

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
# ckpt_path: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train/runs/2023-03-28_17-55-09/checkpoints/last.ckpt"

log_path:
  linear_log: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train_1/runs/2023-04-11_14-38-18"

  linear_mu: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train_1/runs/2023-04-11_14-42-15"

  linear_pu: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train_2/runs/2023-04-11_16-52-40"

  linear_smape: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train_1/runs/2023-04-11_14-36-26"

  linear_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train_3/runs/2023-04-13_23-02-53"

  log_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train_3/runs/2023-04-13_22-59-52"

  pq_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train_3/runs/2023-04-13_23-01-17"

  pu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/train_3/runs/2023-04-13_22-59-40"
