# @package _global_

defaults:
  - _self_
  - model: sadnet.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - representation: pu.yaml
  - loss: l1.yaml
  - hydra: default.yaml


data:
  hq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_hdr
  lq_path: /home/luoleyouluole/Image-Restoration-Experiments/data/test_noise_hdr
  batch_size: 1

task_name: "eval"

log_path:
  # linear_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/edsr_linear_epoch=1726-step=31085.ckpt"

  # pq_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/edsr_pq_epoch=1998-step=35981.ckpt"

  pu_l1: "/home/luoleyouluole/Image-Restoration-Experiments/logs/sadnet_pu_epoch=971-step=68039.ckpt"


results_save_path: "/home/luoleyouluole/Image-Restoration-Experiments/data/res_sadnet/"
